apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-generater
  namespace: logging
  labels:
    app: npm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: npm
  template:
    metadata:
      labels:
        app: npm
    spec:
      containers:
      - name: hello-kubernetes
        image: kherguner/alistirma:fluentd
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 3000
